import clubs from './clubs';

const players = [
	{
		name: 'Nikola Dragan',
		points: 0,
		picks: [
			clubs.ManchesterUnited,
			clubs.Liverpool,
			clubs.ManchesterCity,
			clubs.TottenhamHotspur,
			clubs.Arsenal,
			clubs.WolverhamptonWanderers,
			clubs.Chelsea,
			clubs.Everton,
			clubs.LeicesterCity,
			clubs.WestHamUnited,
			clubs.Bournemouth,
			clubs.Watford,
			clubs.Southampton,
			clubs.AstonVilla,
			clubs.Burnley,
			clubs.CrystalPalace,
			clubs.NewcastleUnited,
			clubs.BrightonHoveAlbion,
			clubs.NorwichCity,
			clubs.SheffieldUnited,
		]
	},
	{
		name: 'Darko Opala',
		points: 0,
		picks: [
			clubs.ManchesterUnited,
			clubs.ManchesterCity,
			clubs.Liverpool,
			clubs.Arsenal,
			clubs.Chelsea,
			clubs.TottenhamHotspur,
			clubs.Everton,
			clubs.LeicesterCity,
			clubs.Watford,
			clubs.Southampton,
			clubs.Burnley,
			clubs.Bournemouth,
			clubs.WolverhamptonWanderers,
			clubs.AstonVilla,
			clubs.CrystalPalace,
			clubs.WestHamUnited,
			clubs.NewcastleUnited,
			clubs.SheffieldUnited,
			clubs.NorwichCity,
			clubs.BrightonHoveAlbion,
		]
	},
	{
		name: 'Milan Todorović',
		points: 0,
		picks: [
			clubs.Arsenal,
			clubs.ManchesterCity,
			clubs.Liverpool,
			clubs.TottenhamHotspur,
			clubs.ManchesterUnited,
			clubs.Chelsea,
			clubs.Everton,
			clubs.WolverhamptonWanderers,
			clubs.LeicesterCity,
			clubs.CrystalPalace,
			clubs.Watford,
			clubs.WestHamUnited,
			clubs.Southampton,
			clubs.Bournemouth,
			clubs.AstonVilla,
			clubs.NewcastleUnited,
			clubs.Burnley,
			clubs.NorwichCity,
			clubs.BrightonHoveAlbion,
			clubs.SheffieldUnited,
		]
	},
	{
		name: 'Nikola Smiljanic',
		points: 0,
		picks: [
			clubs.ManchesterCity,
			clubs.Liverpool,
			clubs.TottenhamHotspur,
			clubs.ManchesterUnited,
			clubs.Arsenal,
			clubs.Chelsea,
			clubs.WolverhamptonWanderers,
			clubs.Everton,
			clubs.LeicesterCity,
			clubs.Bournemouth,
			clubs.WestHamUnited,
			clubs.Watford,
			clubs.CrystalPalace,
			clubs.Burnley,
			clubs.NewcastleUnited,
			clubs.Southampton,
			clubs.AstonVilla,
			clubs.BrightonHoveAlbion,
			clubs.NorwichCity,
			clubs.SheffieldUnited,
		]
	},
	{
		name: 'Nemanja Ciric',
		points: 0,
		picks: [
			clubs.ManchesterCity,
			clubs.Liverpool,
			clubs.ManchesterUnited,
			clubs.TottenhamHotspur,
			clubs.Chelsea,
			clubs.Arsenal,
			clubs.LeicesterCity,
			clubs.WolverhamptonWanderers,
			clubs.Everton,
			clubs.Watford,
			clubs.AstonVilla,
			clubs.Bournemouth,
			clubs.CrystalPalace,
			clubs.WestHamUnited,
			clubs.Burnley,
			clubs.Southampton,
			clubs.NewcastleUnited,
			clubs.NorwichCity,
			clubs.BrightonHoveAlbion,
			clubs.SheffieldUnited,
		]
	},
	{
		name: 'Luka Vučković',
		points: 0,
		picks: [
			clubs.ManchesterCity,
			clubs.Liverpool,
			clubs.TottenhamHotspur,
			clubs.ManchesterUnited,
			clubs.Chelsea,
			clubs.Arsenal,
			clubs.WolverhamptonWanderers,
			clubs.Everton,
			clubs.NewcastleUnited,
			clubs.LeicesterCity,
			clubs.WestHamUnited,
			clubs.Bournemouth,
			clubs.Watford,
			clubs.Southampton,
			clubs.CrystalPalace,
			clubs.AstonVilla,
			clubs.BrightonHoveAlbion,
			clubs.Burnley,
			clubs.SheffieldUnited,
			clubs.NorwichCity,
		]
	},
	{
		name: 'Tamara Mitric',
		points: 0,
		picks: [
			clubs.Liverpool,
			clubs.ManchesterCity,
			clubs.TottenhamHotspur,
			clubs.Chelsea,
			clubs.ManchesterUnited,
			clubs.Arsenal,
			clubs.WolverhamptonWanderers,
			clubs.LeicesterCity,
			clubs.Everton,
			clubs.AstonVilla,
			clubs.Watford,
			clubs.WestHamUnited,
			clubs.CrystalPalace,
			clubs.Southampton,
			clubs.Bournemouth,
			clubs.NewcastleUnited,
			clubs.NorwichCity,
			clubs.Burnley,
			clubs.BrightonHoveAlbion,
			clubs.SheffieldUnited,
		]
	},
	{
		name: 'Vladislav Milivojevic',
		points: 0,
		picks: [
			clubs.ManchesterCity,
			clubs.Liverpool,
			clubs.TottenhamHotspur,
			clubs.Arsenal,
			clubs.ManchesterUnited,
			clubs.Chelsea,
			clubs.WolverhamptonWanderers,
			clubs.LeicesterCity,
			clubs.Everton,
			clubs.CrystalPalace,
			clubs.NewcastleUnited,
			clubs.Watford,
			clubs.AstonVilla,
			clubs.Southampton,
			clubs.Bournemouth,
			clubs.WestHamUnited,
			clubs.BrightonHoveAlbion,
			clubs.NorwichCity,
			clubs.Burnley,
			clubs.SheffieldUnited,
		]
	},
	{
		name: 'Marko Stankov',
		points: 0,
		picks: [
			clubs.ManchesterUnited,
			clubs.Chelsea,
			clubs.ManchesterCity,
			clubs.Arsenal,
			clubs.Liverpool,
			clubs.TottenhamHotspur,
			clubs.Everton,
			clubs.WestHamUnited,
			clubs.CrystalPalace,
			clubs.AstonVilla,
			clubs.NorwichCity,
			clubs.LeicesterCity,
			clubs.Bournemouth,
			clubs.NewcastleUnited,
			clubs.Burnley,
			clubs.Southampton,
			clubs.WolverhamptonWanderers,
			clubs.SheffieldUnited,
			clubs.Watford,
			clubs.BrightonHoveAlbion,
		]
	},
	{
		name: 'Nemanja Fent',
		points: 0,
		picks: [
			clubs.ManchesterUnited,
			clubs.Liverpool,
			clubs.ManchesterCity,
			clubs.Chelsea,
			clubs.Arsenal,
			clubs.TottenhamHotspur,
			clubs.Everton,
			clubs.AstonVilla,
			clubs.WestHamUnited,
			clubs.CrystalPalace,
			clubs.Bournemouth,
			clubs.Burnley,
			clubs.Watford,
			clubs.WolverhamptonWanderers,
			clubs.BrightonHoveAlbion,
			clubs.NewcastleUnited,
			clubs.LeicesterCity,
			clubs.Southampton,
			clubs.NorwichCity,
			clubs.SheffieldUnited,
		]
	},
	{
		name: 'Milan Kosanović',
		points: 0,
		picks: [
			clubs.Liverpool,
			clubs.ManchesterCity,
			clubs.TottenhamHotspur,
			clubs.ManchesterUnited,
			clubs.Chelsea,
			clubs.Arsenal,
			clubs.WolverhamptonWanderers,
			clubs.Everton,
			clubs.LeicesterCity,
			clubs.WestHamUnited,
			clubs.Watford,
			clubs.Southampton,
			clubs.NewcastleUnited,
			clubs.CrystalPalace,
			clubs.Bournemouth,
			clubs.AstonVilla,
			clubs.BrightonHoveAlbion,
			clubs.Burnley,
			clubs.NorwichCity,
			clubs.SheffieldUnited,
		]
	},
	{
		name: 'Nemanja Đuričić',
		points: 0,
		picks: [
			clubs.ManchesterCity,
			clubs.Liverpool,
			clubs.TottenhamHotspur,
			clubs.Chelsea,
			clubs.Arsenal,
			clubs.ManchesterUnited,
			clubs.WestHamUnited,
			clubs.WolverhamptonWanderers,
			clubs.Everton,
			clubs.LeicesterCity,
			clubs.NewcastleUnited,
			clubs.Watford,
			clubs.CrystalPalace,
			clubs.Southampton,
			clubs.Bournemouth,
			clubs.AstonVilla,
			clubs.BrightonHoveAlbion,
			clubs.Burnley,
			clubs.NorwichCity,
			clubs.SheffieldUnited,
		]
	},
	{
		name: 'Zlatko Spasojević',
		points: 0,
		picks: [
			clubs.ManchesterCity,
			clubs.Liverpool,
			clubs.ManchesterUnited,
			clubs.TottenhamHotspur,
			clubs.Chelsea,
			clubs.Arsenal,
			clubs.Everton,
			clubs.WolverhamptonWanderers,
			clubs.LeicesterCity,
			clubs.NewcastleUnited,
			clubs.WestHamUnited,
			clubs.CrystalPalace,
			clubs.AstonVilla,
			clubs.Southampton,
			clubs.Watford,
			clubs.Bournemouth,
			clubs.BrightonHoveAlbion,
			clubs.SheffieldUnited,
			clubs.Burnley,
			clubs.NorwichCity,
		]
	},
	{
		name: 'Tijana Popov',
		points: 0,
		picks: [
			clubs.ManchesterCity,
			clubs.Liverpool,
			clubs.TottenhamHotspur,
			clubs.Chelsea,
			clubs.ManchesterUnited,
			clubs.Arsenal,
			clubs.WolverhamptonWanderers,
			clubs.Everton,
			clubs.CrystalPalace,
			clubs.LeicesterCity,
			clubs.WestHamUnited,
			clubs.NewcastleUnited,
			clubs.Watford,
			clubs.Bournemouth,
			clubs.AstonVilla,
			clubs.Southampton,
			clubs.Burnley,
			clubs.NorwichCity,
			clubs.BrightonHoveAlbion,
			clubs.SheffieldUnited,
		]
	},
	{
		name: 'Branko Gvozdenovic',
		points: 0,
		picks: [
			clubs.ManchesterCity,
			clubs.Liverpool,
			clubs.ManchesterUnited,
			clubs.TottenhamHotspur,
			clubs.Arsenal,
			clubs.Chelsea,
			clubs.Everton,
			clubs.LeicesterCity,
			clubs.WestHamUnited,
			clubs.WolverhamptonWanderers,
			clubs.CrystalPalace,
			clubs.Watford,
			clubs.Bournemouth,
			clubs.BrightonHoveAlbion,
			clubs.NewcastleUnited,
			clubs.Southampton,
			clubs.AstonVilla,
			clubs.Burnley,
			clubs.NorwichCity,
			clubs.SheffieldUnited,
		]
	},
	{
		name: 'Srđan Donevski',
		points: 0,
		picks: [
			clubs.ManchesterUnited,
			clubs.ManchesterCity,
			clubs.Chelsea,
			clubs.Liverpool,
			clubs.Arsenal,
			clubs.LeicesterCity,
			clubs.TottenhamHotspur,
			clubs.NewcastleUnited,
			clubs.Everton,
			clubs.AstonVilla,
			clubs.SheffieldUnited,
			clubs.WestHamUnited,
			clubs.CrystalPalace,
			clubs.Southampton,
			clubs.Bournemouth,
			clubs.BrightonHoveAlbion,
			clubs.WolverhamptonWanderers,
			clubs.Burnley,
			clubs.NorwichCity,
			clubs.Watford,
		]
	},
	{
		name: 'Nikolina Ninković',
		points: 0,
		picks: [
			clubs.ManchesterUnited,
			clubs.ManchesterCity,
			clubs.Liverpool,
			clubs.Chelsea,
			clubs.Arsenal,
			clubs.TottenhamHotspur,
			clubs.NewcastleUnited,
			clubs.AstonVilla,
			clubs.Everton,
			clubs.WestHamUnited,
			clubs.Southampton,
			clubs.CrystalPalace,
			clubs.NorwichCity,
			clubs.LeicesterCity,
			clubs.Watford,
			clubs.Burnley,
			clubs.WolverhamptonWanderers,
			clubs.SheffieldUnited,
			clubs.Bournemouth,
			clubs.BrightonHoveAlbion,
		]
	},
	{
		name: 'Marija Petrovic',
		points: 0,
		picks: [
			clubs.Arsenal,
			clubs.ManchesterUnited,
			clubs.AstonVilla,
			clubs.ManchesterCity,
			clubs.TottenhamHotspur,
			clubs.CrystalPalace,
			clubs.Chelsea,
			clubs.Everton,
			clubs.Liverpool,
			clubs.WestHamUnited,
			clubs.Burnley,
			clubs.NewcastleUnited,
			clubs.NorwichCity,
			clubs.LeicesterCity,
			clubs.SheffieldUnited,
			clubs.BrightonHoveAlbion,
			clubs.Southampton,
			clubs.Watford,
			clubs.Bournemouth,
			clubs.WolverhamptonWanderers,
		]
	},
	{
		name: 'Dajana Miljanovic',
		points: 0,
		picks: [
			clubs.ManchesterCity,
			clubs.Liverpool,
			clubs.TottenhamHotspur,
			clubs.Arsenal,
			clubs.Everton,
			clubs.ManchesterUnited,
			clubs.LeicesterCity,
			clubs.Chelsea,
			clubs.WestHamUnited,
			clubs.WolverhamptonWanderers,
			clubs.Watford,
			clubs.CrystalPalace,
			clubs.Bournemouth,
			clubs.Southampton,
			clubs.AstonVilla,
			clubs.NorwichCity,
			clubs.NewcastleUnited,
			clubs.Burnley,
			clubs.SheffieldUnited,
			clubs.BrightonHoveAlbion,
		]
	},
	{
		name: 'Milana Crvenković 🏆',
		points: 0,
		picks: [
			clubs.ManchesterCity,
			clubs.Liverpool,
			clubs.TottenhamHotspur,
			clubs.Arsenal,
			clubs.Chelsea,
			clubs.ManchesterUnited,
			clubs.Everton,
			clubs.WolverhamptonWanderers,
			clubs.WestHamUnited,
			clubs.Burnley,
			clubs.AstonVilla,
			clubs.CrystalPalace,
			clubs.NewcastleUnited,
			clubs.LeicesterCity,
			clubs.Watford,
			clubs.Bournemouth,
			clubs.Southampton,
			clubs.BrightonHoveAlbion,
			clubs.NorwichCity,
			clubs.SheffieldUnited,
		]
	},
	{
		name: 'Slobodan Trajković',
		points: 0,
		picks: [
			clubs.ManchesterCity,
			clubs.Liverpool,
			clubs.ManchesterUnited,
			clubs.Chelsea,
			clubs.TottenhamHotspur,
			clubs.Arsenal,
			clubs.Everton,
			clubs.WolverhamptonWanderers,
			clubs.LeicesterCity,
			clubs.NewcastleUnited,
			clubs.WestHamUnited,
			clubs.Watford,
			clubs.CrystalPalace,
			clubs.Bournemouth,
			clubs.AstonVilla,
			clubs.Southampton,
			clubs.BrightonHoveAlbion,
			clubs.NorwichCity,
			clubs.Burnley,
			clubs.SheffieldUnited,
		]
	},
	{
		name: 'Milos Davidovic ',
		points: 0,
		picks: [
			clubs.ManchesterCity,
			clubs.Liverpool,
			clubs.TottenhamHotspur,
			clubs.ManchesterUnited,
			clubs.Chelsea,
			clubs.Arsenal,
			clubs.WolverhamptonWanderers,
			clubs.Everton,
			clubs.NewcastleUnited,
			clubs.LeicesterCity,
			clubs.WestHamUnited,
			clubs.Bournemouth,
			clubs.Watford,
			clubs.Southampton,
			clubs.CrystalPalace,
			clubs.AstonVilla,
			clubs.BrightonHoveAlbion,
			clubs.Burnley,
			clubs.SheffieldUnited,
			clubs.NorwichCity,
		]
	},
	{
		name: 'Maksim Bogunović',
		points: 0,
		picks: [
			clubs.ManchesterCity,
			clubs.Liverpool,
			clubs.TottenhamHotspur,
			clubs.Chelsea,
			clubs.WolverhamptonWanderers,
			clubs.Arsenal,
			clubs.ManchesterUnited,
			clubs.WestHamUnited,
			clubs.Everton,
			clubs.LeicesterCity,
			clubs.CrystalPalace,
			clubs.NewcastleUnited,
			clubs.Bournemouth,
			clubs.NorwichCity,
			clubs.BrightonHoveAlbion,
			clubs.SheffieldUnited,
			clubs.Watford,
			clubs.Burnley,
			clubs.AstonVilla,
			clubs.Southampton,
		]
	},
	{
		name: 'Mihajlo Radmilović',
		points: 0,
		picks: [
			clubs.Liverpool,
			clubs.ManchesterCity,
			clubs.Chelsea,
			clubs.TottenhamHotspur,
			clubs.ManchesterUnited,
			clubs.Arsenal,
			clubs.CrystalPalace,
			clubs.Everton,
			clubs.LeicesterCity,
			clubs.Southampton,
			clubs.WestHamUnited,
			clubs.AstonVilla,
			clubs.Bournemouth,
			clubs.NewcastleUnited,
			clubs.NorwichCity,
			clubs.Watford,
			clubs.Burnley,
			clubs.SheffieldUnited,
			clubs.BrightonHoveAlbion,
			clubs.WolverhamptonWanderers,
		]
	},
	{
		name: 'Brzi Boro',
		points: 0,
		picks: [
			clubs.Chelsea,
			clubs.Liverpool,
			clubs.Arsenal,
			clubs.ManchesterCity,
			clubs.TottenhamHotspur,
			clubs.ManchesterUnited,
			clubs.Everton,
			clubs.LeicesterCity,
			clubs.Bournemouth,
			clubs.CrystalPalace,
			clubs.NewcastleUnited,
			clubs.NorwichCity,
			clubs.BrightonHoveAlbion,
			clubs.Burnley,
			clubs.WestHamUnited,
			clubs.Southampton,
			clubs.SheffieldUnited,
			clubs.Watford,
			clubs.AstonVilla,
			clubs.WolverhamptonWanderers,
		]
	},
	{
		name: 'Dragana Krstić',
		points: 0,
		picks: [
			clubs.ManchesterCity,
			clubs.Arsenal,
			clubs.Liverpool,
			clubs.ManchesterUnited,
			clubs.Chelsea,
			clubs.TottenhamHotspur,
			clubs.WestHamUnited,
			clubs.Everton,
			clubs.CrystalPalace,
			clubs.AstonVilla,
			clubs.WolverhamptonWanderers,
			clubs.Watford,
			clubs.LeicesterCity,
			clubs.BrightonHoveAlbion,
			clubs.Burnley,
			clubs.NewcastleUnited,
			clubs.NorwichCity,
			clubs.Southampton,
			clubs.Bournemouth,
			clubs.SheffieldUnited,
		]
	},
];

const weeks = [
	[
		clubs.ManchesterCity,
		clubs.ManchesterUnited,
		clubs.Liverpool,
		clubs.Burnley,
		clubs.BrightonHoveAlbion,
		clubs.TottenhamHotspur,
		clubs.Arsenal,
		clubs.SheffieldUnited,
		clubs.Bournemouth,
		clubs.Everton,
		clubs.CrystalPalace,
		clubs.LeicesterCity,
		clubs.WolverhamptonWanderers,
		clubs.NewcastleUnited,
		clubs.AstonVilla,
		clubs.NorwichCity,
		clubs.Southampton,
		clubs.Watford,
		clubs.Chelsea,
		clubs.WestHamUnited,
	],
	[
		clubs.Liverpool,
		clubs.Arsenal,
		clubs.ManchesterCity,
		clubs.ManchesterUnited,
		clubs.BrightonHoveAlbion,
		clubs.TottenhamHotspur,
		clubs.Bournemouth,
		clubs.SheffieldUnited,
		clubs.Everton,
		clubs.Burnley,
		clubs.NorwichCity,
		clubs.LeicesterCity,
		clubs.WolverhamptonWanderers,
		clubs.CrystalPalace,
		clubs.Chelsea,
		clubs.WestHamUnited,
		clubs.AstonVilla,
		clubs.NewcastleUnited,
		clubs.Southampton,
		clubs.Watford,
	],
	[
		clubs.Liverpool,
		clubs.ManchesterCity,
		clubs.Arsenal,
		clubs.LeicesterCity,
		clubs.ManchesterUnited,
		clubs.Burnley,
		clubs.TottenhamHotspur,
		clubs.BrightonHoveAlbion,
		clubs.SheffieldUnited,
		clubs.CrystalPalace,
		clubs.Bournemouth,
		clubs.Everton,
		clubs.Chelsea,
		clubs.WestHamUnited,
		clubs.WolverhamptonWanderers,
		clubs.AstonVilla,
		clubs.NorwichCity,
		clubs.Southampton,
		clubs.NewcastleUnited,
		clubs.Watford,
	],
	[
		clubs.Liverpool,
		clubs.ManchesterCity,
		clubs.LeicesterCity,
		clubs.CrystalPalace,
		clubs.Arsenal,
		clubs.Everton,
		clubs.WestHamUnited,
		clubs.ManchesterUnited,
		clubs.TottenhamHotspur,
		clubs.SheffieldUnited,
		clubs.Chelsea,
		clubs.Burnley,
		clubs.Southampton,
		clubs.NewcastleUnited,
		clubs.Bournemouth,
		clubs.BrightonHoveAlbion,
		clubs.WolverhamptonWanderers,
		clubs.AstonVilla,
		clubs.NorwichCity,
		clubs.Watford,
	],
];

const teams = {
	[clubs.AstonVilla]: 0,
	[clubs.BrightonHoveAlbion]: 0,
	[clubs.Arsenal]: 0,
	[clubs.WolverhamptonWanderers]: 0,
	[clubs.Bournemouth]: 0,
	[clubs.WestHamUnited]: 0,
	[clubs.LeicesterCity]: 0,
	[clubs.Everton]: 0,
	[clubs.ManchesterUnited]: 0,
	[clubs.CrystalPalace]: 0,
	[clubs.TottenhamHotspur]: 0,
	[clubs.Chelsea]: 0,
	[clubs.NewcastleUnited]: 0,
	[clubs.Watford]: 0,
	[clubs.NorwichCity]: 0,
	[clubs.Burnley]: 0,
	[clubs.SheffieldUnited]: 0,
	[clubs.Liverpool]: 0,
	[clubs.ManchesterCity]: 0,
	[clubs.Southampton]: 0,
};

export { players, weeks, teams };